nikhilkalige/docblockr

- lib/docblockr.js
Kills a Deprecation Cop warning.
configDefaults has been deprecated since v0.133.0: https://github.com/atom/atom/commit/f57dbfd9f531c847f8e1ce34beab2b526f71
> Use a config schema instead of configDefaults.

- lib/docblockr-worker.js
Kills a Deprecation Cop warning.
editor.scopesForBufferPosition has been deprecated since v0.139.0: atom/atom@137eeab
> Use editor.scopeDescriptorForBufferPosition.

- lib/docblockr-worker.js
Kills a Deprecation Cop warning.
getActiveEditor has been deprecated since v0.153.0: atom/atom@714cbc9
> Use Workspace::getActiveTextEditor()

- lib/docblockr-worker.js
Kills a Deprecation Cop warning.
lineLengthForBufferRow has been deprecated since v0.125.0: atom/atom@5e21d1c
lineForBufferRow has been deprecated since v0.125.0: atom/atom@b516f5a
> Use editor.lineTextForBufferRow(row)

- lib/docblockr-worker.js
this fixes the issue i previously reported yesterday!
> grammar scope name for cpp is 'cpp' (at least on new atom versions)

- lib/languages/rust.js
- spec/dataset/rust.yaml
This will prevent an error, when using block comments.
> Add parse_var methode to the RustParser

- lib/docblockr-worker.js
When pressing tab inside a comment `DocBlockrAtom.prototype.indent_command` is executed. This will copy the indention of the the line above or just do a normal indentation if the line above is not indented.
The normal indentation shouldn't be just a tab, rather fall back to the default behavior.
This will fix #163
> Remove hardcoded tab (`\t`) indentation

- keymaps/docblockr.json
This will prevent the `sippets:Expand` Event from overriding this event and fix #167
> Make selector for the `docblockr:parse-tab` event more specific

- lib/docblockr-worker.js
Fixed the issue that one more asterisk is added when starting a new line from a block comments.
Solution:
I modified the regular expression for the case that an asterisk needs to be added. The new expression will check that if a string is ended by an slash(/), a new asterisk will be added only when the string is not ended by an slash(/).
Example:
In this case:
```
/**********
* asides *
**********/ <-- enter here, it will create a new line without asterisk
```
In the cases below they still work:
```
/*
* <-- enter here, it will create a new line with an asterisk
*
* foo bar  <-- enter here, it will also create a new line with an asterisk
*/
```
> Fixed the issue #131 that adds an asterisk when starting a new line from the end of block comments.

- lib/languages/javascript.js
- spec/dataset/languages/javascript.yaml
now checks for:
- async
- export
- default
<body>
<footer>
> update javascript functionRegex to test for es-next syntax (#203)

- lib/docblockr-worker.js
The regex wasn't matching the line. I think Atom use to includes newlines on to the beginning of text buffers, this is no longer the case. This fixes the `Wrap Lines` command.
Ref #162 
cc @MoritzKn
Edit: Actually, looks like due to Atom's reporting system, #162 is actually an accumulation of multiple errors, all with the same error message `Uncaught TypeError: Cannot read property '1' of null` - this PR will resolve the issues regarding the wrap lines function, but not all reported in that thread. The issue should remain open.
> Fixes #162

- lib/docblockr-worker.js
Pressing enter at the end of the first line will give you the correct second line.
```js
///# @name
///# 
```
Instead of
```js
///# @name
/// 
```
> Updated to grab everything associated with the comment

- CHANGELOG.md
- README.md
- lib/docblockr-worker.js
- lib/docblockr.js
Hi, this is an awesome package, thanks.
I use block comments sometimes and noticed that the Docblockr support for these isn't as strong as for full docstrings.
I added an option "c_style_block_comments", defaulting off. With the setting off the current behaviour should be unchanged.
With it on, `/* <enter>` becomes
/*
* <cursor here>
*/
And similarly, like when you push enter on the top line of an existing docstring it doesn't create a new one;
/* <cursor here; user pushes enter>Foo
* ...
*/
becomes
/*
* <cursor here>Foo
* ...
*/
This is just a light usability tweak but it would be very nice to have.
Cheers
David
> Add (optional) support for c-style block comments

- lib/languages/javascript.js
when I input some code like this
```javascript
function func ({}) {}
```
and then input `/**` to use docblockr
`Uncaught TypeError: Cannot read property 'value' of null `
> Prevent exception if arguments can't be parsed

- lib/docsparser.js
> Fix typo regarding return type in DocsParser.prototype.format_function (#251)

- lib/docsparser.js
- lib/languages/javascript.js
- spec/dataset/languages/javascript.yaml
Like described in #34 the `@constructor` annotation should be added if the function name starts with a upper case letter.
> Add @constructor annotation to JavaScript constructor functions | Implements #34 

- lib/languages/cpp.js
- spec/dataset/languages/cpp.yaml
Fixed #234 and #273 and also added specs. The specs cover these bugs as well as other basic functionality of parsing C++ code.
> Fix C++ parsing bugs

- lib/docblockr-worker.js
This fixes a subtle bug related to text inputs in Atom's docks. I introduced the bug myself in #266, so I suppose it's only fair that I fix it.
1. Open a JavaScript file containing a multiline comment.
2. Place the cursor within the multiline comment.
3. Click into the "Commit message" box in the GitHub integration.
4. Press <kbd>Enter</kbd>.
- Newline added to "Commit message".
- Newline added to comment in active text editor.
- Look first for the editor attached to the keyboard event, rather than using `atom.workspace.getActiveTextEditor()` first.
> Check `event.target` before `getActiveTextEditor()`

- README.md
- lib/docblockr-worker.js
- lib/languages/processing.js
- spec/dataset/languages/processing.yaml
- spec/language.spec.js
Adds support for [processing](https://processing.org/) by extending the Java parser as suggested by @audreyseo.
> Add support for Processing

- lib/docsparser.js
- lib/languages/javascript.js
- spec/dataset/languages/javascript.yaml
Example: 
```js
const object = {
* funcName(var) {}
*funcName(var) {}
}
```
The leading asterisk will be processed as a mark of exist comment before, so I made a little fix to bypass it.
> Handle ES2015 generator shorthand for Object

- lib/docsparser.js
- lib/languages/typescript.js
This is an updated version of #172. It should address: #134, #201, #242, #243
I've tried to implement the original review suggestions into this as well as maintain code style with what already existed.
The original goals were:
- function `@param`s should not include type
- constructor functions should not have `@return`
- constructor function argument name parser should strip `public` and `private` keywords
- var block should not include `@type`
> Feature: Typescript/Typedoc updates

- lib/docblockr-worker.js
- lib/docblockr.js
- lib/docsparser.js
- lib/languages/actionscript.js
- lib/languages/coffee.js
- lib/languages/cpp.js
- lib/languages/java.js
- lib/languages/javascript.js
- lib/languages/objc.js
- lib/languages/php.js
- lib/languages/processing.js
- lib/languages/rust.js
- lib/languages/sass.js
- lib/languages/typescript.js
- spec/dataset/languages/cpp.yaml
- spec/dataset/languages/java.yaml
- spec/dataset/languages/javascript.yaml
- spec/dataset/languages/php.yaml
- spec/dataset/languages/processing.yaml
- spec/dataset/languages/rust.yaml
- spec/dataset/languages/sass.yaml
Also contains some slight cleanup that was possible after the change.
See commit messages for details.
I'll do one more pull request after this, with some general cleanup before I start working on the customizability feature (which will probably result in a non backwards compatible version).
It'll also fix all the bugs I can find.
Sorry these pull requests are a bit too general, and not focused on just one change. Just let me know and I'll split these up into multiple ones.
I'm hoping this makes it faster overall, not having to go through ~10 different pull requests.
> Migrate to `class` syntax throughout the project

- README.md
- lib/docblockr-worker.js
- lib/docblockr.js
- lib/languages/rust.js
- spec/dataset/languages/rust.yaml
First off I apologise for my poor javascript. Not my native language.
Here I add a simple extension to add rust parsing of functions and formatting the output.
The formatted output tries to adhere to the format recommended by the [rust book](https://doc.rust-lang.org/rust-by-example/meta/doc.html) and the machine readable [specs](https://deterministic.space/machine-readable-inline-markdown-code-cocumentation.html)
Comments, suggests, outright crying over poor js code blasphemys are expected and encouraged.
Fixes: #331 
Fixes: #347
> Do some basic rust parsing of functions
